--!strict
--[[
    chalk Adhesive

    Adhesive library for chalk.
--]]

--]] Services
--]] Modules
--]] Settings
--]] Constants
--]] Variables
--]] Functions
--]] Module
local Adhesive = {}
Adhesive.__index = Adhesive

--// TODO: Type Definitions
--// TODO: Constructor
--> This is going to allow different objects to connect together
--> When rendering shapes:
-->     Make list of all shapes in registry
-->     Search through all adhesive objects
-->     Render those first
-->     Remove all Object ID's from the Registry
-->     Search through the new list
-->     Render those

return Adhesive